reed-college/paneity

.travis.yml
tutor/tests.py
tutor/tests/test_models.py

Start tests

---

tutor/templates/tutor/index.html
tutor/views.py

home page now has courses listed for which tutoring is available

updated index/course page with a list of courses

---

tutor/templates/tutor/index.html

.created unqiue links for each class, created fake bio tutor Chicken Combo.

updated courses page

---

tutor/templates/tutor/startstop.html

added "Stop Tutoring" button + Javascript popup warning about closing the window, front end of page is p much done

Front End of Start/Stop Page

---

tutor/templates/tutor/index.html

added reed logos, text/background colors, font styling, etc etc

made front end of homepage sexier

---

tutor/templates/tutor/startstop.html
tutor/templates/tutor/tutors.html

added fun colors and fonts and logos and such

front end of StartStop + Tutors page(s)

---

tutor/templates/tutor/base.html
tutor/templates/tutor/index.html
tutor/templates/tutor/startstop.html
tutor/templates/tutor/tutors.html

made the HTML/web titles more representative of their function/contents

changed titles of the web pages

---

.gitmodules
.travis.yml
spirit

I removed the spirit submodules. Many fewer headaches await

Remove submodule

---

tutor/static/paneitystyle.css
tutor/static/spiritstyle.css
tutor/templates/tutor/index.html
tutor/templates/tutor/startstop.html
tutor/templates/tutor/tutors.html

we have two buttons, one that links to the tutoring homepage, and the other that links to the forum home page

added a nav bar to tutoring app

---

tutor/static/paneitystyle.css
tutor/templates/tutor/index.html
tutor/templates/tutor/tutors.html

changed wording on tutoring homepage

homepage_text

---

tutor/static/paneitystyle.css

made border of highlight effect/color change on hover less boxy, added transition delays to make the effect a bit smoother

navbar edits

---

paneity/settings.py
paneity/urls.py
requirements.txt
tutor/templates/base.html
tutor/templates/django_private_chat/dialogs.html
tutor/templates/tutor/base.html
tutor/templates/tutor/tutors.html
tutor/views/main.py

I replaced google hangouts with a django app called django-private-chat. All of the google api stuff is still there, but there are no links to it anymore. My next step will be getting rid of the google api stuff.

Added django-private-chat

---

tutor/static/paneitystyle.css
tutor/templates/tutor/tutors.html
tutor/templatetags/tutor_extras.py
tutor/views/main.py

I added a column to the tutors page that says when they last logged in

Last login

---

tutor/templates/django_private_chat/dialogs.html
tutor/templatetags/tutor_extras.py
tutor/tests/test_templatetags.py
tutor/tests/test_views.py

I added a button on the chat page that will start a videochat between a student and a tutor. 
The service I used is called jitsi meet and you can read about it here: https://jitsi.org/jitsi-meet/

Added video chat back in

---

paneity/settings.py
tutor/templates/base.html
tutor/templates/tutor/tutorchat.html
tutor/tests/test_views.py
tutor/urls.py
tutor/views/main.py

I made a page that will notify a tutor if they get a message from anyone and then direct them to that chat page. This page is not linked to on the main site, so we'll need to add that later. Also I need to add a way to see if you got a message while not on this page.

added page for tutors to get directed to chats

---

tutor/static/paneitystyle.css
tutor/templates/tutor/base.html

moved tutor login so that it's next to the other links in the banner/header

tutor login for tutoring app

---

tutor/static/paneitystyle.css
tutor/templates/tutor/base.html
tutor/templates/tutor/tutors.html

matched styling to the Tutors table, deleted link and styling for the old dropin/officehrs external html page

drop in + office hrs styling

---

tutor/templates/tutor/index.html

Closes #144 
If the user is not enrolled in any courses, then the "enrolled courses" header does not appear on the courses page.

Enrolled Courses Fix

---

tutor/tests/test_models.py

I was looking at some old tests and I thought my comments could be more helpful

updated comments to be more helpful

---

tutor/static/css/error403.css
tutor/templates/error/403.html

we can further improve it, but I made some quick changes

Improved 403 page

---

tutor/static/css/base.css
tutor/templates/tutor/base.html

this tells the user "you are logged in as <username>" or it says "you are not logged in"

Login info

---

tutor/static/css/error404.css
tutor/templates/404.html
tutor/urls.py
tutor/views/main.py

It's hard to know what the page even looks like, because to view it, you have to set DEBUG to False, but that makes it so static files, like CSS, aren't loaded. So, it might look terrible, but the page is there.

made a 404 page, not styled (very much)

---

tutor/templates/django_private_chat/dialogs.html
tutor/templatetags/tutor_extras.py

made the tutorchat dialog.html show first and last names not usernames

---

paneity/settings.py
tutor/templatetags/tutor_extras.py

This changes the message history in the admin view, but not on the dialogs webpage

changed the timezone to pacific in settings.py

---

tutor/static/css/base.css
tutor/static/css/index.css
tutor/templates/tutor/base.html
tutor/templates/tutor/index.html

Made nav bar for mobile

---

tutor/static/css/django_private_chat.css
tutor/templates/django_private_chat/dialogs.html

Redoing this pr because I fucked up

Chat styling

---

tutor/static/css/django_private_chat.css
tutor/templates/django_private_chat/dialogs.html

Here's what the chat now looks like:

Chat styling changes

---

tutor/templates/tutor/base.html
tutor/templates/tutor/index.html
tutor/templates/tutor/tutors.html

I think the username div was competing with the \<h2\> title tag for space, so the title was off center.
Closes #180

made title centered again

---

tutor/static/css/django_private_chat.css
tutor/templates/django_private_chat/dialogs.html

I had changed an id selector to a class selector, and the js wasn't recognizing the element.

Added back the online/offline status on chat page

---

tutor/static/js/tutorchat.js
tutor/templates/tutor/tutorchat.html

Sorry, but with my last pr, I forgot to make it so that when you receive a new message, that new element is also clickable.
Closes #209

made new rows clickable

---

tutor/static/css/django_private_chat.css

made it go to right side

---

tutor/tests/test_templatetags.py

Closes #208 
I just made some tests for the template tags

Tutor template tags tests

---

.eslintrc.json
.gitignore
package.json
tutor/static/js/dialogs.js
tutor/static/js/index.js
tutor/static/js/startstop.js
tutor/static/js/tutorchat.js
tutor/templates/django_private_chat/dialogs.html
tutor/templates/tutor/index.html

I installed a linter called [eslint](http://eslint.org/) and corrected all of the errors it threw on our javascript files. It still has some warnings I need to get rid of.

Linted the javascript

---

tutor/templates/tutor/base.html

It gets the banner from `_banner.html` in spirit now
Closes #264

made it so base imports banner

---

tutor/static/js/dialogs.js
tutor/static/js/inbox.js
tutor/static/js/tutors.js
tutor/templates/tutor/tutors.html

The javascript files will throw an error telling you what you need to do or what you need to import if there is something missing.
Closes #213

Require js

---

auth/apps.py
auth/tests.py
auth/views.py
paneity/settings_prod.py
paneity/urls.py

made logout button work on halp
